[package]
name = "hrdf-parser"
version = "0.10.0"
edition = "2024"
description = "This library is dedicated to the parsing of the HRDF format. For the moment, it can only parse the Swiss version of the HRDF format."
repository = "https://github.com/urban-travel/hrdf-parser"
license-file = "LICENSE"

[dependencies]
chrono = { version = "0.4.45", features = ["serde"] }
hex = "0.4.3"
log = "0.4.34"
nom = { version = "8.0.0", features = ["alloc", "std"] }
postcard = { version = "1.1.3", features = ["use-std"] }
reqwest = "0.13.5"
rustc-hash = "2.1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11"
strum = "0.28.0"
strum_macros = "0.28.0"
test-log = "0.2.21"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["macros", "rt", "rt-multi-thread"] }
url = "2.5.8"
zip = "8.6.0"

[dev-dependencies]
flate2 = "1.1.10"
mimalloc = "0.1.52"
# For -Zminimal-versions
native-tls = "0.2.18"
pretty_assertions = "1.4.1"
serde_json = "1.0.151"

[profile.dev]
opt-level = 3
